---
all:
  children:
    pubnix:
      hosts:
        atl-pubnix:
          ansible_host: "{{ lookup('env', 'PUBNIX_HOST') | default('test.atl.sh', true) }}"
          ansible_user: root
          ansible_port: 22
