---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: Restart gmid
  ansible.builtin.systemd:
    name: gmid
    state: restarted
- name: Restart gophernicus
  ansible.builtin.systemd:
    name: gophernicus
    state: restarted
