---
ssh_ports:
  - 22
  - 2222
ssh_permit_root_login: "prohibit-password"
ssh_password_authentication: "no"
ssh_max_auth_tries: 3
ssh_login_grace_time: 30
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_allow_groups: "pubnix root sudo"

fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_maxretry: 5


firewall_allowed_tcp_ports:
  - "22" # SSH primary
  - "2222" # SSH secondary
  - "70" # Gopher
  - "80" # HTTP
  - "443" # HTTPS
  - "1965" # Gemini
  - "21"   # FTP Control
  - "40000:40100" # FTP Passive Data

firewall_rate_limit_ssh: true
